### ISSUE TITLE
mb some implementation?

### ISSUE THREAD

**Issue by 0exp** [ahydrax/mumble-telegram-bot#1]
subj jojoba pepega van-lav-van-life :)

**Comment by ahydrax** [comment]
pagadi malenko tam libka v native ot'ebnula

**Comment by 0exp** [comment]
oke horosho ia znachit nabludau

**Comment by 0exp** [comment]
PASHEL KODIK. AI HARASHO

**Comment by 0exp** [comment]
https://github.com/andrewlock/StronglyTypedId

a eto norm tema? laik stavit? dlia pacanov laik vsegda pripriatan - eto sviatoe.
dotnety laik - po jize straik

**Comment by ahydrax** [comment]
eto norm codogenerated typesafe magic

**Comment by 0exp** [comment]
postavil star. type safety, reflection-blablabla (net etot sluchai, no vse ravno), metamagia, kodogeneracia (ne vsegda, no pacanam razreshau) - eto prikolno

**Comment by 0exp** [comment]
mne nravitsa.

potom pridu eshe raz posmotru
